// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMN-RUFtA3hMLSIunoNoYx8hhxHlEFbhw',
    appId: '1:990355535533:web:5198feaadb219ea64df824',
    messagingSenderId: '990355535533',
    projectId: 'projectecomarce',
    authDomain: 'projectecomarce.firebaseapp.com',
    databaseURL: 'https://projectecomarce-default-rtdb.firebaseio.com',
    storageBucket: 'projectecomarce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwbR86mQuGpgRNbfkdLHkOppL6bOKf0L8',
    appId: '1:990355535533:android:b125c3ac09d5d9ce4df824',
    messagingSenderId: '990355535533',
    projectId: 'projectecomarce',
    databaseURL: 'https://projectecomarce-default-rtdb.firebaseio.com',
    storageBucket: 'projectecomarce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV-RNneOmTqej8myDXM_I2jjGL1JPy8g0',
    appId: '1:990355535533:ios:2e0d061a418958974df824',
    messagingSenderId: '990355535533',
    projectId: 'projectecomarce',
    databaseURL: 'https://projectecomarce-default-rtdb.firebaseio.com',
    storageBucket: 'projectecomarce.appspot.com',
    androidClientId: '990355535533-31tlnkn7prvse54362lg9peiaqc2pdml.apps.googleusercontent.com',
    iosClientId: '990355535533-e4rfbk7h0psn4rtm5dfb0012hct8v3ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.myvendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV-RNneOmTqej8myDXM_I2jjGL1JPy8g0',
    appId: '1:990355535533:ios:2e0d061a418958974df824',
    messagingSenderId: '990355535533',
    projectId: 'projectecomarce',
    databaseURL: 'https://projectecomarce-default-rtdb.firebaseio.com',
    storageBucket: 'projectecomarce.appspot.com',
    androidClientId: '990355535533-31tlnkn7prvse54362lg9peiaqc2pdml.apps.googleusercontent.com',
    iosClientId: '990355535533-e4rfbk7h0psn4rtm5dfb0012hct8v3ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.myvendor',
  );
}
